syntax = "proto3";

package vulpescloud.cluster.v2;

option java_multiple_files = true;
option java_package = "de.vulpescloud.proto.cluster.v2";

enum NodeState {
  NODE_STATES_OFFLINE_UNSPECIFIED = 0;
  NODE_STATES_BOOTING = 1;
  NODE_STATES_ONLINE = 2;
  NODE_STATES_DRAINING = 3;
  NODE_STATES_UNKNOWN = 4;
}

message NodeModule {
  string name = 1;
  repeated string authors = 2;
  string description = 3;
  string version = 4;
  string website = 5;
  bool copyToServices = 6;
  string servicePlatforms = 7;
  bool neededOnAllNodes = 8;
  NodeModuleState state = 9;
}

enum NodeModuleState {
  NODE_MODULE_STATE_UNSPECIFIED = 0;
  NODE_MODULE_STATE_UNLOADED = 1;
  NODE_MODULE_STATE_LOADED = 2;
  NODE_MODULE_STATE_ENABLED = 3;
}

message Node {
  string name = 1;
  string uuid = 2;
  string grpc_address = 3;
  int32 grpc_port = 4;
}

message NodeSnapshot {
  string name = 1;
  string uuid = 2;

  NodeState state = 3;

  int64 players_on_node = 4;

  int64 timestamp = 5;
  int64 startup_timestamp = 6;

  SystemSnapshot system = 7;
  ServiceSnapshot services = 8;

  map<string, string> attributes = 9;
}

message SystemSnapshot {
  CpuSnapshot cpu = 1;
  MemorySnapshot memory = 2;
}

message CpuSnapshot {
  int32 cores = 1;

  double usage = 2;
}

message MemorySnapshot {
  int64 total = 1;
  int64 used = 2;
  int64 available = 3;
}

message ServiceSnapshot {
  int32 count = 1;

  int64 memory_limit = 2;
  int64 memory_used = 3;
  int64 memory_reserved = 4;
  int64 memory_available = 5;
}