syntax = "proto3";

package vulpescloud.node.v1;

option java_multiple_files = true;
option java_package = "de.vulpescloud.proto.node.v1";

enum NodeStates {
  NODE_STATES_OFFLINE_UNSPECIFIED = 0;
  NODE_STATES_BOOTING = 1;
  NODE_STATES_ONLINE = 2;
  NODE_STATES_DRAINING = 3;
  NODE_STATES_UNKNOWN = 4;
}

message Node {
  string name = 1;
  string uuid = 2;
  string grpc_address = 3;
  int32 grpc_port = 4;
  NodeStates state = 5;
  int32 max_memory = 6;
  bool head = 7;
  int64 boot_timestamp = 8;
  map<string, string> attributes = 9;
}

message NodeSnapshot {
  string name = 1;
  string uuid = 2;
  NodeStates state = 3;
  int32 used_memory = 4;
  double cpu_usage = 5;
  int32 online_players = 6;
  int64 timestamp = 8;
  map<string, string> attributes = 9;
}

message GetAllNodesRequest {}

message GetAllNodesResponse {
  repeated Node nodes = 1;
}

message GetNodeByNameRequest {
  string name = 1;
}

message GetNodeByNameResponse {
  Node node = 1;
}

message GetNodeSnapshotRequest {
  string name = 1;
}

message GetNodeSnapshotResponse {
  NodeSnapshot snapshot = 1;
}

message PlayerCommandSource {
  string playerName = 1;
  string playerUuid = 2;
  string playerProxyServiceName = 3;
  string playerServerServiceName = 4;
}

message UserCommandSource {
  string username = 1;
  map<string, string> extraData = 2;
}

message ExecuteCommandRequest {
  oneof source {
    PlayerCommandSource playerSource = 1;
    UserCommandSource userSource = 2;
  }
  string command = 3;
}

message ExecuteCommandResponse {
  bool success = 1;
  repeated string output = 2;
}

message TabCompleteRequest {
  oneof source {
    PlayerCommandSource playerSource = 1;
    UserCommandSource userSource = 2;
  }
  string command = 3;
}

message TabCompleteResponse {
  repeated string suggestions = 1;
}

message PingRequest {

}

message PingResponse {
  
}

message HeartbeatRequest {
  Node node = 1;
}

message HeartbeatResponse {

}

message AuthenticateNodeRequest {
  string node_name = 1;
  string node_uuid = 2;
}

message AuthenticateNodeResponse {
  bool success = 1;
  string message = 2;
}

service ClusterAPIService {
  rpc GetAllNodes(GetAllNodesRequest) returns (GetAllNodesResponse);
  rpc GetNodeByName(GetNodeByNameRequest) returns (GetNodeByNameResponse);
  rpc GetNodeSnapshot(GetNodeSnapshotRequest) returns (GetNodeSnapshotResponse);
  rpc TabComplete(TabCompleteRequest) returns (TabCompleteResponse);
  rpc ExecuteCommand(ExecuteCommandRequest) returns (ExecuteCommandResponse);
  rpc Ping(PingRequest) returns (PingResponse);
  rpc Heartbeat(HeartbeatRequest) returns (HeartbeatResponse);
  rpc AuthenticateNode(AuthenticateNodeRequest) returns (AuthenticateNodeResponse);
}
